name: Dance Photography
favicon: null
layout_spectrum: 0.27598319691605866
typography_spectrum: 0.4523051190190017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.30535100190900266
  lightness: 0.3505435527767986
  saturation: 0.6978576499968767
  rhythmicContrast: 0.39751340076327324
purpose: []
