layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3125
  brandStrength: 0.5
  lightness: 0.3505436
  brandColors:
    - '#726964'
    - '#0C0807'
    - '#C9B6AF'
    - '#AF0F17'
    - '#F1E4DD'
  rhythmicContrast: 0.5
typography_spectrum: 0.0358423
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Dance Photography
