name: Dance Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#905863'
    - '#35211a'
    - '#d0b9b1'
    - '#2f4678'
    - '#b98391'
  brandStrength: 1
  lightness: 0.3505436
  saturation: 1
  rhythmicContrast: 0.3975134
purpose: []
