name: Dance Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9a606f'
    - '#f5eded'
    - '#d0b9b1'
    - '#304f85'
  brandStrength: 0.5
  lightness: 0.3505436
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
