name: Dance Photography
favicon: null
layout_spectrum: 0.37046
typography_spectrum: 0.14807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b0a'
    - '#9ca4b8'
    - '#e3ebff'
    - '#757c90'
    - '#5d0c13'
  brandStrength: 0.30535100190900266
  lightness: 0.3505435527767986
  saturation: 0.6978576499968767
  rhythmicContrast: 0.39751340076327324
purpose: []
